### ISSUE TITLE
v3 requires felix to have RW access to policies which allows compromised nodes to bypass policies

### ISSUE THREAD

**Issue by jhorwit2** [projectcalico/calico#1653]
## Expected Behavior

I expect that calico node/felix should not need write privileges to policies they're supposed to enforce. 

## Current Behavior

The documentation states that felix requires RW to policies. https://docs.projectcalico.org/v3.0/reference/advanced/etcd-rbac/calico-etcdv3-paths

v2 required non-root access 
https://docs.projectcalico.org/v2.6/reference/advanced/etcd-rbac/calico-etcdv2-paths

## Context

This prevents us from using v3 since it's not as secure as v2.

**Comment by caseydavenport** [comment]
@fasaxc @robbrockbank is this actually correct?

That sounds like a documentation bug to me - I'm not aware of anything that's changed which requires Felix to write data into etcd.

**Comment by jhorwit2** [comment]
This seems to apply to most things on that documentation page. Looking through the CNI code it only needs to modify workload endpoints and read profiles but the docs say it requires full RW on the key space as well. .

**Comment by robbrockbank** [comment]
@caseydavenport I'm not aware of anything - sounds like a docs bug.

**Comment by caseydavenport** [comment]
Fixed in https://github.com/projectcalico/calico/pull/1670

**Comment by jhorwit2** [comment]
@caseydavenport this seems to only have been partially fixed. The CNI plugin for example still mentions it requires full RW privs.

**Comment by caseydavenport** [comment]
yeah, the more detailed tables were consolidated in the corresponding v3.0 docs.

I've raised https://github.com/projectcalico/calico/issues/1698 to cover the others since this issue was mostly just discussing Felix.
