### ISSUE TITLE
Extensive log spew in calico-node container regarding watchers

### ISSUE THREAD

**Issue by weikinhuang** [projectcalico/calico#1894]
## Expected Behavior

Not to get extensive logs (roughly 100k every day per node)

## Current Behavior

Getting these log lines every few seconds

```
2018-04-16 16:22:01.593 [INFO][77] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="BGPPeer (custom)"
2018-04-16 16:22:01.594 [INFO][77] watcher.go 83: Kubernetes watcher/converter started resource="BGPPeer (custom)"
2018-04-16 16:22:07.302 [INFO][77] watcher.go 124: Watch event indicates a terminated watcher resource="IPPool (custom)"
2018-04-16 16:22:07.302 [INFO][77] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="IPPool (custom)"
2018-04-16 16:22:07.302 [INFO][77] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-04-16 16:22:07.302 [INFO][77] watchercache.go 129: Stopping previous watcher ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-04-16 16:22:07.302 [INFO][77] watchersyncer.go 153: Error received in main syncer event processing loop error=watch terminated (closedByRemote:true): terminating error event from Kubernetes watcher: closed by remote
2018-04-16 16:22:07.303 [INFO][77] watcher.go 83: Kubernetes watcher/converter started resource="IPPool (custom)"
2018-04-16 16:23:19.491 [INFO][77] watcher.go 124: Watch event indicates a terminated watcher resource="IPPool (custom)"
2018-04-16 16:23:19.491 [INFO][77] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="IPPool (custom)"
2018-04-16 16:23:19.491 [INFO][77] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-04-16 16:23:19.491 [INFO][77] watchercache.go 129: Stopping previous watcher ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-04-16 16:23:19.491 [INFO][77] watchersyncer.go 153: Error received in main syncer event processing loop error=watch terminated (closedByRemote:true): terminating error event from Kubernetes watcher: closed by remote
2018-04-16 16:23:19.492 [INFO][77] watcher.go 83: Kubernetes watcher/converter started resource="IPPool (custom)"
2018-04-16 16:23:21.295 [INFO][77] watcher.go 124: Watch event indicates a terminated watcher resource="BGPConfiguration (custom)"
2018-04-16 16:23:21.295 [INFO][77] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="BGPConfiguration (custom)"
2018-04-16 16:23:21.295 [INFO][77] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/bgpconfigurations"
2018-04-16 16:23:21.295 [INFO][77] watchercache.go 129: Stopping previous watcher ListRoot="/calico/resources/v3/projectcalico.org/bgpconfigurations"
2018-04-16 16:23:21.296 [INFO][77] watchersyncer.go 153: Error received in main syncer event processing loop error=watch terminated (closedByRemote:true): terminating error event from Kubernetes watcher: closed by remote
2018-04-16 16:23:21.297 [INFO][77] watcher.go 83: Kubernetes watcher/converter started resource="BGPConfiguration (custom)"
2018-04-16 16:24:00.678 [INFO][77] watcher.go 124: Watch event indicates a terminated watcher resource="BGPPeer (custom)"
2018-04-16 16:24:00.678 [INFO][77] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="BGPPeer (custom)"
2018-04-16 16:24:00.678 [INFO][77] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/bgppeers"
2018-04-16 16:24:00.678 [INFO][77] watchercache.go 129: Stopping previous watcher ListRoot="/calico/resources/v3/projectcalico.org/bgppeers"
2018-04-16 16:24:00.678 [INFO][77] watchersyncer.go 153: Error received in main syncer event processing loop error=watch terminated (closedByRemote:true): terminating error event from Kubernetes watcher: closed by remote
2018-04-16 16:24:00.679 [INFO][77] watcher.go 83: Kubernetes watcher/converter started resource="BGPPeer (custom)"
2018-04-16 16:24:34.844 [INFO][77] watcher.go 124: Watch event indicates a terminated watcher resource="IPPool (custom)"
2018-04-16 16:24:34.844 [INFO][77] watchercache.go 127: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-04-16 16:24:34.844 [INFO][77] watchersyncer.go 153: Error received in main syncer event processing loop error=watch terminated (closedByRemote:true): terminating error event from Kubernetes watcher: closed by remote
2018-04-16 16:24:34.844 [INFO][77] watchercache.go 129: Stopping previous watcher ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-04-16 16:24:34.844 [INFO][77] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="IPPool (custom)"
2018-04-16 16:24:34.845 [INFO][77] watcher.go 83: Kubernetes watcher/converter started resource="IPPool (custom)"
```

## Steps to Reproduce (for bugs)

Set up a cluster with bootkube and calico as the cni

## Your Environment

* Calico version: 3.0.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: coreos
* Link to your project (optional):

**Comment by turbo-ele** [comment]
having the same issues on centos7 and customly setup clusters via kubeadm

## Steps to Reproduce (for bugs)
Set up a cluster with kubeadm and calico as the cni

## Your Environment
Calico version: 3.0.4
Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
Operating System and version: centos7

I'm planning to update to the newest version 3.1.3 but haven't found anything regarding this issue in the release notes, so i assume it's not fixed yet?

**Comment by tmjd** [comment]
Yes please try the newer version, I believe it was improved. It may have not been an obvious release note that it was improved or might have not been release noted.

**Comment by turbo-ele** [comment]
thank you, will try and see if its fixed in a newer version

**Comment by weikinhuang** [comment]
@tmjd I just updated to 3.1.3 and am still getting these messages
```
2018-06-13 21:55:34.323 [INFO][79] watcher.go 83: Kubernetes watcher/converter started resource="BGPConfiguration (custom)"
2018-06-13 21:55:45.867 [INFO][79] watcher.go 124: Watch event indicates a terminated watcher resource="IPPool (custom)"
2018-06-13 21:55:45.868 [INFO][79] watcher.go 85: Kubernetes watcher/converter stopped, closing result channel resource="IPPool (custom)"
2018-06-13 21:55:45.868 [INFO][79] watchercache.go 156: Starting watch sync/resync processing ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-06-13 21:55:45.868 [INFO][79] watchercache.go 256: Stopping previous watcher ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2018-06-13 21:55:45.868 [INFO][79] watchersyncer.go 196: Error received in main syncer event processing loop error=watch terminated (closedByRemote:true): terminating error event from Kubernetes watcher: closed by remote```

**Comment by caseydavenport** [comment]
I think we should probably just drop the log level down to debug on those logs. 

Anyone care to submit a PR?
