### ISSUE TITLE
Push multi-arch manifests to quay.io

### ISSUE THREAD

**Issue by invidian** [projectcalico/calico#4227]
## Expected Behavior

Replacing `calico/cni:v1.17.0` with `quay.io/calico/cni:v1.17.0` should work on ARM platforms.

## Current Behavior

`quay.io` registry is returning different manifests than `docker/io`, even though Quay supports multi-arch manifests.

Manifest from `docker.io`:
```console
$ docker manifest inspect calico/cni:v3.17.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 946,
         "digest": "sha256:b033b5237cfd233974c5dff2379ad83b81cb938f48083d392c83a1cead537149",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 946,
         "digest": "sha256:5f95f08ee0ee629d29653a90bdbdb4a5fa9d6bc2b251083809dbb781e81fa7a3",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 946,
         "digest": "sha256:5775ca2345692726ede299f038f8c00006edf1ae0e90fecf6dcd59547eeca979",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      }
   ]
}
```

Manifes from `quay.io`:

```
$ docker manifest inspect quay.io/calico/cni:v3.17.0
{
        "schemaVersion": 2,
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "config": {
                "mediaType": "application/vnd.docker.container.image.v1+json",
                "size": 3364,
                "digest": "sha256:94159b46f8d8265255a5ac26812e70c6199d2d9a8ff01e1b18c13dc1940a515b"
        },
        "layers": [
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 18091,
                        "digest": "sha256:65c8c9bc8b9d70f6caf351e4e5f119a0ace1523b4cb5d7544695b387158e4696"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 4064,
                        "digest": "sha256:aa83ec2d163535222f2446327c1a6bb1c823fdda81a30b37cd086912d52f3648"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 44027141,
                        "digest": "sha256:c40275fca228cdb20742bfd4db7d3322c144e6aebfe1f3955d5adcac66f63a22"
                }
        ]
}
```

Sample multi-arch manifest from `quay.io`:

```console
$ docker manifest inspect quay.io/kinvolk/checkpoint:43ec4b414e44f202e07bf43e57d2b5ffbcfd4415
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:3f2f0340764b1fb7ec432b824316e5e7b9802c960b059679e90d0709b241244d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:44e6cb23dda113ec15b67ed5232fc2ac104925cb0da10cd6e17fa9cde1dcd28c",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

## Context

Because of new Docker Hub pull limits, we would like to use Quay as a main registry to pull Calico images from, to make cluster creation process more reliable (kinvolk/lokomotive#1225), as currently we sometimes hit limits when creating virtual clusters (so using the same public IP all the time).

**Comment by caseydavenport** [comment]
When we implemented our release infrastructure quay.io did not support multi-arch manifests, and so we have separate images pushed to quay.

If quay.io now supports multi-arch manifests, that is great news! We should update our release process to publish those as well.

**Comment by aquam8** [comment]
@invidian I think you closed this by mistake as the Quay.io images still do not have ARM64 support...

**Comment by invidian** [comment]
Indeed, it seems at least one of the image is still missing ARM64 support:
```json
$ docker manifest inspect quay.io/calico/cni:v3.19.1
{
        "schemaVersion": 2,
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "config": {
                "mediaType": "application/vnd.docker.container.image.v1+json",
                "size": 3363,
                "digest": "sha256:5749e8b276f9b5aea2683d8a0d59afd05a2be478f5092fbaadc4715f4db76e5a"
        },
        "layers": [
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 18093,
                        "digest": "sha256:740c37ed87bd03bc3193d1382b3b836328022c78911d62d0f9b508d9a37abc1a"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 4063,
                        "digest": "sha256:5019aa621b5376714f3e9aa04a6f264a857f639c536a587b5a1670b1e2699e62"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 48310687,
                        "digest": "sha256:b0c76401258249c3fb3308cde0f71a626d225a5ede0dcef81c23b430cbb716da"
                }
        ]
}
```

**Comment by frozenprocess** [comment]
Fixed in release-v3.21+ 
```
docker manifest inspect calico/cni:release-v3.21
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 946,
         "digest": "sha256:2fc54a8e3cb84c76f426c4b4ba9751b1b06f9dcbfa3d6acfaebb1363edcc6bd8",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1369,
         "digest": "sha256:fa29d367597f2146ead38d8d4b686928569772d883da859e121bdeb0b5aec63e",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 946,
         "digest": "sha256:ca5fc085a81ab94d82f2f47ca48c921782ec3271362b99e830bd42fbd33be4f3",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 946,
         "digest": "sha256:25a15fa9b307c9eedd4e84888db252974eabd39bd2dee062bca7eed303e4da81",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      }
   ]
}

```

```
docker manifest inspect quay.io/calico/cni:v3.21.0
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 3832,
		"digest": "sha256:19c5757ec6bba4c818602b0f32956d2007047fc47489e80b7d5f3e13e3b01465"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 18091,
			"digest": "sha256:7dc2279c2579694186cab3116a6e13f6fe38b9f236956e001190801bd64f6507"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 4063,
			"digest": "sha256:e6c0d3276a0157a4fb0171f76048dd7571a0ea9f492f254ee976c95850ea13ea"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 25121884,
			"digest": "sha256:4c6527eed8e05f9f59adfc4dd229f53884b3735993d1079c8fa1c007b2212398"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 3227126,
			"digest": "sha256:717fdafbf6dd0c283286a06966bfa46ccab2139fa8f84ba3fb881688a067b79f"
		},
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 53170478,
			"digest": "sha256:ad7e9cce3f21a924d6a17a87215aee2be32926a61d8183f02fbe8540671e4e19"
		}
	]
}

```

**Comment by invidian** [comment]
Awesome!
