### ISSUE TITLE
Kubelet stuck in pod deletion due to "WorkloadEndpoint not found" error from the CNI plugin

### ISSUE THREAD

**Issue by tommasopozzetti** [projectcalico/calico#4235]
## Expected Behavior
The CNI plugin should be able to handle the case of a missing WorkloadEndpoint (possibly due to a previous partial deletion or an ungraceful node shutdown) during pod deletion and allow the Kubelet to terminate the teardown process to remove the container.

## Current Behavior
It seems that it sometimes happens that a pause container has exited but is still to be deleted while the corresponding WorkloadEndpoint has already been deleted. If this happens, the Kubelet tries to repeat the teardown process for the pod to clean up the resources, however it sometimes fails with the following errors
```
Dec 02 14:24:19 <node-name> kubelet[3704]: W1202 21:24:19.890679    3704 cni.go:331] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "8341b8e2b959c4f976b055efb924969d43764cbc71878de05a46ea09a394c7c0"
Dec 02 14:24:19 <node-name> kubelet[3704]: E1202 21:24:19.946602    3704 cni.go:385] Error deleting <container-name>/8341b8e2b959c4f976b055efb924969d43764cbc71878de05a46ea09a394c7c0 from network calico/k8s-pod-network: WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(<workloadendpoint-name>)" not found
Dec 02 14:24:19 <node-name> kubelet[3704]: E1202 21:24:19.947349    3704 remote_runtime.go:128] StopPodSandbox "8341b8e2b959c4f976b055efb924969d43764cbc71878de05a46ea09a394c7c0" from runtime service failed: rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod "<pod-name>" network: WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(<workloadendpoint-name>)" not found
Dec 02 14:24:19 <node-name> kubelet[3704]: E1202 21:24:19.947387    3704 kuberuntime_gc.go:170] Failed to stop sandbox "8341b8e2b959c4f976b055efb924969d43764cbc71878de05a46ea09a394c7c0" before removing: rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod "<pod-name>" network: WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(<workloadendpoint-name>)" not found
```
and when this happens, the Kubelet gets stuck trying to clean up the pod once a minute and never being able to.
One extra info I noticed is that this seems to happen always with pods originating from StatefulSets, so it might be related to the fact that the name of the pod does not change when it is rescheduled.

## Possible Solution
Upon further investigation, it seems that the CNI plugin already deals with the case of a missing WorkloadEndpoint and ignores it, as expected, to allow the Kubelet to proceed with teardown and cleanup (for example [here](https://github.com/projectcalico/cni-plugin/blob/v3.17.0/pkg/k8s/k8s.go#L507)). However, it seems that there is a case where that check is not successful even if the issue is indeed that the resource is missing. The issue seems to be related to the fact that the check is performed by looking at the type of the error, however libcalico returns [here](https://github.com/projectcalico/libcalico-go/blob/release-v3.17/lib/backend/k8s/resources/workloadendpoint.go#L212) a generic kubernetes error rather than a calico specific one, which then fails the test and therefore is interpreted as a connection error to the datastore.
I tested recompiling the cni plugin binary by changing that line to
```golang
return nil, K8sErrorToCalico(kerrors.NewNotFound(apiv3.Resource("WorkloadEndpoint"), key.String()), k)
``` 
and that seemed to fix the error as the Kubelet was finally able to ignore the error and proceed with the cleanup.

## Your Environment
* Calico version 3.16.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.18.8
* Operating System and version: Linux CentOS 8

**Comment by lmm** [comment]
Thanks for digging into this @tommasopozzetti . It does look like the cni del is catching Calico errors only. I wonder if we're returning a k8s error from libcalico-go to maybe make it more generally consumable by other projects maybe. @caseydavenport wdyt?

**Comment by caseydavenport** [comment]
No reason - I am pretty sure that is just a bug and it should instead be a Calico error type that is returned. Good sleuthing @tommasopozzetti!

Would you be interested in submitting a PR with the fix?

**Comment by caseydavenport** [comment]
This may also be relevant: https://github.com/projectcalico/calico/issues/4084

**Comment by tommasopozzetti** [comment]
@caseydavenport Created a PR with the change that should resolve the issue projectcalico/libcalico-go#1363

**Comment by nktpro** [comment]
@tommasopozzetti Release `v3.18.2` was supposed to address this according to the release notes referencing the PR above. However we've just upgraded to `v3.18.2` (and even rebooted all nodes) and re-tested, this issue still persisted. 

This is a **severe** regression which would prevent any `VolumeAttachment` to be released, such that a stateful pod can transition from a drained node to another one. It compromises High Availability of a Kubernetes cluster with any stateful workloads. 

Here are the steps to reproduce:

- Have any `StatefulSet` with mounted `PVCs`
- Drain a node where there's a replica of the `StatefulSet` above for maintenance with `kubectl drain ...`
- Observe `kubelet` logs of the drained node. `kubelet` is now stuck in a loop with this error:

```
"Failed killing the pod" err="failed to \"KillPodSandbox\" for \"XXXXX" with KillPodSandboxError: \"rpc 
error: code = Unknown desc = failed to destroy network for pod sandbox XXXXXX: Error while removing pod from CNI network \\\"k8s-pod-network\\\": WorkloadEndpoint.crd.projectcalico.org \\\"WorkloadEndpoint(XXXXXXX-eth0)\\\" not found\"" podName="XXXXX"
```
- The corresponding `VolumeAttachment` that was bound to that pod would now be stuck. As a consequence, a new `StatefulSet` replica will be scheduled on a new node but will stays in `ContainerCreating` state.

**Comment by eplightning** [comment]
Can confirm this still happens after upgrade to 3.18.2 as well.

Maybe the dependency didn't get upgraded for cni-plugin? https://github.com/projectcalico/cni-plugin/blob/v3.18.2/go.mod seems to point to commit older than the cherrypick

**Comment by eplightning** [comment]
I can confirm that 3.19.0 fixed the issue for me.
```
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.232 [WARNING][776555] k8s.go 519: WorkloadEndpoint does not exist in the datastore, moving forward with the clean up ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013" WorkloadEndpoint="[..]
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.233 [INFO][776555] k8s.go 561: Cleaning up netns ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013"
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.233 [INFO][776555] k8s.go 568: Releasing IP address(es) ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013"
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.233 [INFO][776555] utils.go 196: Calico CNI releasing IP address ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013"
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.272 [INFO][776563] ipam_plugin.go 407: Releasing address using handleID ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013" HandleID="k8s-pod-network.448449f6d52b831d96a91324454563b8228779f7fdb4f9a9>
May 01 11:43:12 [..]-kube-n1 env[849]: time="2021-05-01T11:43:12Z" level=info msg="About to acquire host-wide IPAM lock." source="ipam_plugin.go:348"
May 01 11:43:12 [..]-kube-n1 env[849]: time="2021-05-01T11:43:12Z" level=info msg="Acquired host-wide IPAM lock." source="ipam_plugin.go:363"
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.273 [INFO][776563] ipam.go 1410: Releasing all IPs with handle 'k8s-pod-network.448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013'
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.289 [WARNING][776563] ipam_plugin.go 424: Asked to release address but it doesn't exist. Ignoring ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013" HandleID="k8s-pod-network.448449f6d52b831d96a913>
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.289 [INFO][776563] ipam_plugin.go 435: Releasing address using workloadID ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013" HandleID="k8s-pod-network.448449f6d52b831d96a91324454563b8228779f7fdb4f9>
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.289 [INFO][776563] ipam.go 1410: Releasing all IPs with handle 'argocd.argocd-application-controller-0'
May 01 11:43:12 [..]-kube-n1 env[849]: time="2021-05-01T11:43:12Z" level=info msg="Released host-wide IPAM lock." source="ipam_plugin.go:369"
May 01 11:43:12 [..]-kube-n1 env[849]: 2021-05-01 11:43:12.293 [INFO][776555] k8s.go 574: Teardown processing complete. ContainerID="448449f6d52b831d96a91324454563b8228779f7fdb4f9a93b9d8ea557cce013
```

**Comment by nktpro** [comment]
I confirmed this is resolved in `3.19.0` release as well. Thanks @caseydavenport

**Comment by mgleung** [comment]
Release `v3.18.3` should also include this change since it was missed in `v3.18.2` for those wanting to stay on Calico v3.18

**Comment by caseydavenport** [comment]
Thanks for the help and patience! Glad we got it sorted out.
