### ISSUE TITLE
Incompatible ipset protocol version (7) will cause problems

### ISSUE THREAD

**Issue by uablrek** [projectcalico/calico#5011]
## Expected Behavior

Calico can handle different `ipset` protocol versions. At least 6-7.

## Current Behavior

If K8s upgrades to `ipset` >= v7.0 outgoing connects from pods fail.

## Possible Solution

Upgrade the calico image to include `ipset` v7.x since it's backward compatible.

## Steps to Reproduce (for bugs)

1. Make sure K8s is upgraded to use `ipset` v7.x (this is non-trivial if installed with kubeadm)
2. Use proxy-mode=ipvs (uses ipset)
3. Try an outgoing connect from a pod

The `kube-proxy` (v1.22.2) image includes `ipset` v6.38. It must be changed to some v7.x version. How that is done I can't say. I start `kube-proxy` as a program (no container) so for me it's simply to change the `ipset` on the node.

## Context

While this isn't a problem at the moment, it will be the day K8s upgrades to iset v7.x

## Your Environment

* Calico version: calico/cni:v3.19.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s
* Operating System and version: Own. But Ubuntu 20.04.3 LTS uses ipset v7.5 at the moment
* Link to your project (optional):

**Comment by dghubble** [comment]
> it will be [a problem] the day K8s upgrades to iset v7.x

Kubernetes v1.23.0 `kube-proxy` does use v.7.x. Calico v1.22.x Pods show the OP's error and will never be Ready. So the time has come.

```
ipset --version
ipset v7.10, protocol version: 7
```

**Comment by Dr-Shadow** [comment]
There is probably other compatibility issues since protocol version 7 seems to be used in my case.

Ubuntu host -- k8s node :
```
ubuntu@k8s-master-01:~$ sudo ipset version
ipset v7.10, protocol version: 7
```
Ubuntu host -- calico-node pod
```
❯ kubectl exec -it -n calico-system calico-node-zq7kg -- bash
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), install-cni (init)
[root@k8s-master-01 /]# ipset version
ipset v7.1, protocol version: 7
[root@k8s-master-01 /]# ipset list
Name: KUBE-NODE-PORT-TCP
Type: bitmap:port
Revision: 3
Header: range 0-65535
Size in memory: 8264
References: 0
Number of entries: 0
Members:
ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.
```

**Comment by dghubble** [comment]
Our distro marked Calico as not supported with Kuberntes v1.23 due to this incompatibility

**Comment by Meroje** [comment]
On Fedora 35
```
2021-12-31 17:55:39.777 [INFO][47966] felix/ipsets.go 312: Retrying after an ipsets update failure... family="inet"
2021-12-31 17:55:39.779 [ERROR][47966] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port,net with revision 8 not supported by userspace.\n"
2021-12-31 17:55:39.779 [WARNING][47966] felix/ipsets.go 322: Failed to resync with dataplane error=exit status 1 family="inet"
```

**Comment by uablrek** [comment]
@Meroje What linux kernel version do Fedora 35 use?

I am using linux-5.15.2 and only protocol versions 6-7 is supported, not version 8.
Please see; https://github.com/torvalds/linux/blob/8008293888188c3923f5bd8a69370dae25ed14e5/include/uapi/linux/netfilter/ipset/ip_set.h#L16-L18

**Comment by Meroje** [comment]
It's on 5.15.6 indeed not even the next 5.16 seem to not have that number

**Comment by lwr20** [comment]
> Our distro marked Calico as not supported with Kuberntes v1.23 due to this incompatibility

FWIW, our overnight runs (on ubuntu 20.04) show Calico working just fine with k8s 1.23, so this *isn't* a blanket incompatibility.

**Comment by Dr-Shadow** [comment]
> > Our distro marked Calico as not supported with Kuberntes v1.23 due to this incompatibility
> 
> FWIW, our overnight runs (on ubuntu 20.04) show Calico working just fine with k8s 1.23, so this _isn't_ a blanket incompatibility.

That's probably because you're using proxy-mode=iptables

**Comment by Meroje** [comment]
I got errors when using ipvs mode for dualstack use, iptables is fine on my 1.23 cluster

**Comment by Dr-Shadow** [comment]
Since CentOS 8 is on EOL right now, this is most likely to be fixed once calico node switches from CentOS 8 to CentOS Stream 9 since it includes ipset v7.11 & kernel 5.14.
CentOS Stream 9 got released a few weeks ago.

**Comment by dghubble** [comment]
Yeah, reverting kube-proxy to iptables mode avoids the issue of course, but we'd like to stick to ipvs. We're using other CNIs until Calico supports this again.

**Comment by Dr-Shadow** [comment]
I can confirm from Slack that there was some work from @song-jiang for switching the base images to CentOS Stream 9 which would provide a sufficient version of ipset. So at least we can tell that this would be fixed in a future release.

Until then ipvs proxy mode SHOULD be disabled to make Calico work on kubernetes >= 1.23.

**Comment by invidian** [comment]
Hmm, I wonder what I do wrong that Calico v3.21.2 works fine for me with kube-proxy in ipvs mode. Could it be that I miss some configuration, so kube-proxy is runing in ipvs mode while calico keeps using iptables?

**Comment by Dr-Shadow** [comment]
> Hmm, I wonder what I do wrong that Calico v3.21.2 works fine for me with kube-proxy v1.23.1 in ipvs mode. Could it be that I miss some configuration, so kube-proxy is runing in ipvs mode while calico keeps using iptables?

Can you check calico-node logs and ipset version on host VS on calico-node pod ?

**Comment by uablrek** [comment]
Please note that _incoming_ traffic works with proxy-mode=ipvs. Outgoing doesn't.

**Comment by invidian** [comment]
```
$ kex calico-node-fzgvv -c calico-node -- ipset --version
ipset v7.1, protocol version: 7
$ ssh ... sudo ipset --version
ipset v7.6, protocol version: 7
$ kex kube-proxy-99mb7 -- ipset --version
ipset v7.10, protocol version: 7
$ klo calico-node-zs9jh | grep ipvs
2022-01-12 08:53:13.568 [INFO][71] felix/driver.go 78: Kube-proxy in ipvs mode, enabling felix kube-proxy ipvs support.
2022-01-12 08:53:13.892 [INFO][71] felix/int_dataplane.go 1036: Linux interface state changed. ifIndex=6 ifaceName="kube-ipvs0" state="up"
2022-01-12 08:53:13.896 [INFO][71] felix/int_dataplane.go 1521: Received interface update msg=&intdataplane.ifaceUpdate{Name:"kube-ipvs0", State:"up", Index:6}
$ klo kube-proxy-78q2f | grep -i ipvs
I1217 00:03:42.452605       1 server_others.go:269] "Using ipvs Proxier"
I1217 00:03:42.452630       1 server_others.go:271] "Creating dualStackProxier for ipvs"
```

**Comment by Dr-Shadow** [comment]
What about the kernel version ?

**Comment by invidian** [comment]
I'm running `5.10.84-flatcar`.

**Comment by Dr-Shadow** [comment]
Interesting, this kernel version doesn't include bucketsize in all hash types for the ipset kernel module that's why you seem to have no issues.

**Comment by dghubble** [comment]
This isn't fixed in Calico v3.22.0

**Comment by lazystone** [comment]
I just updated my toy installation(one node) - k8s 1.23.3, Calico 3.22.0 - seems to work fine.

**Comment by xmudrii** [comment]
Looks like this isn't fixed in v3.22.0. We have tested it as well and the issue is still present. calico-node is never getting ready and logs are spamming the following error:

```
2022-02-02 09:41:07.002 [ERROR][38249] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port with revision 6 not supported by userspace.\n"
```

**Comment by lazystone** [comment]
3.22 works for me.

Below is some info If it helps to troubleshot:

```bash
kubectl get pods -n kube-system -o jsonpath="{.items[*].spec.containers[*].image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c
      1 docker.io/calico/kube-controllers:v3.22.0
      1 docker.io/calico/node:v3.22.0
      2 k8s.gcr.io/coredns/coredns:v1.8.6
      1 k8s.gcr.io/etcd:3.5.1-0
      1 k8s.gcr.io/kube-apiserver:v1.23.3
      1 k8s.gcr.io/kube-controller-manager:v1.23.3
      1 k8s.gcr.io/kube-proxy:v1.23.3
      1 k8s.gcr.io/kube-scheduler:v1.23.3
      
uname -a
Linux NAS 5.14.0-1020-oem #22-Ubuntu SMP Thu Jan 13 18:22:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xmudrii** [comment]
@lazystone Are you running kube-proxy in the iptables or IPVS mode? The default is iptables mode, and it works fine on 1.23. The issue is that running kube-proxy in the IPVS mode doesn't work on 1.23 with Calico at all.

**Comment by Dr-Shadow** [comment]
@xmudrii is right v3.22.0 is missing the PR #5485 
You can directly use the latest calico/node image with the tag master, it should be working.
Master history : [https://github.com/projectcalico/calico/commits/master/node](https://github.com/projectcalico/calico/commits/master/node)
v3.22.0 history : [https://github.com/projectcalico/calico/commits/v3.22.0/node](https://github.com/projectcalico/calico/commits/v3.22.0/node)

**Comment by Dr-Shadow** [comment]
@caseydavenport can you include this PR #5485 in the next release ?

**Comment by song-jiang** [comment]
FYI: The ipset changes is not part of v3.22.0 since it takes more time to get everything fully tested. It should be in v3.22.1.

**Comment by song-jiang** [comment]
Raised https://github.com/projectcalico/calico/pull/5561

**Comment by lazystone** [comment]
@xmudrii I use [metallb](https://metallb.org/installation/), so it's `ipvs`

**Comment by caseydavenport** [comment]
Yep that's right, the fix has been merged to master but needs cherry-picking to the v3.22 branch still. Once that's done it will be in v3.22.1.

We didn't get this into v3.22.0 because the fix came in a bit later and we had already entered code freeze.

**Comment by leoweiyu** [comment]
I am running 1.23.4 with Calico3.22 on Ubuntu 20.04.4 LTS in IPVS mode, and I can confirm this is still NOT fixed.

**Comment by lazystone** [comment]
I mentioned above that it works for me in IPVS mode. But I was wrong - It starts but outgoing connections fail.

**Comment by Dr-Shadow** [comment]
I can confirm this would be fixed in the next release.
calico/node:latest (not v3.22.0) is working with ipvs mode once you include it with a custom ImageSet
Have a look here : https://projectcalico.docs.tigera.io/maintenance/image-options/imageset
Or wait for the next release (v3.22.1)

**Comment by leoweiyu** [comment]
I have just rolled out 3.22.1 and I am still seeing the same error message

`kk get daemonset -n kube-system calico-node -o yaml|grep image:
        image: docker.io/calico/node:v3.22.1
        image: docker.io/calico/cni:v3.22.1
        image: docker.io/calico/cni:v3.22.1
      - image: docker.io/calico/pod2daemon-flexvol:v3.22.1`

and still seeing
`2022-03-06 22:51:02.647 [ERROR][72103] felix/ipsets.go 574: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip,port,ip with revision 6 not supported by userspace.\n"`

**Comment by lwr20** [comment]
@leoweiyu Would you mind raising as a new Issue (and link to this one) please?

**Comment by leoweiyu** [comment]
@lwr20 , sorry was busy for the past few days, yeah the last comment in #5717 make sense to me, i am running k8s on arm system and seems 3.22.1-arm did not get the latest fix as 3.22.1-amd
