### ISSUE TITLE
Performance issue with eBPF enabled in a multi-node setup (working without eBPF)

### ISSUE THREAD

**Issue by EugenMayer** [projectcalico/calico#5575]
When  traffic comes into the calico network (from the edge), so something that crosses a LoadBalancer into the network, the performance is maxed out at 5MB/s (iperf3). 

There is no ingress in between, it is plain `LoadBalancer` and the iperf3.

## Expected Behavior
It should at least perform as well as non-eBPF, which is about 4GB/s

## Current Behavior
Activating eBPF reduced the max. bandwidth to 5MB/s - this can be measured using iperf3 without and ingress (synthetic benchmark) or using an ingress and `docker push` workloads.

## Possible Solution
I have none

## Steps to Reproduce (for bugs)

It does only happen in multi-node environments. With a single node, the performance is normal with eBPF.
- enable eBPF (we use VXLAN (non CrossSubnet), non BGP) 
- use iperf e.g. using helm, e.g. via https://github.com/EugenMayer/helm-charts/tree/main/charts/iperf3
- measure the performance from any server in the same network / being close (to ensure no other bottlenecks)
- Switch from eBPF to Iptables - try the benchmark again. Should be a lot better

We used/tested this with quick-setups via RKE2 or k3s. E.g. using k3s use

```
curl -fL https://get.k3s.io | K3S_KUBECONFIG_MODE="640" INSTALL_K3S_EXEC="server --disable-kube-proxy --no-deploy=servicelb --disable=servicelb --disable-network-policy --flannel-backend=none --disable traefik --disable local-storage" sh -
```

Then install calico / tigera operator via the helm chart https://artifacthub.io/packages/helm/projectcalico/tigera-operator

## Context
- setup using terraform for 100% reproduceable / conform testing setups
- we deployed several setups from scratch without anything else the iperf and calico - no fuzz or extra layer
- we have an MTU of 1342 due to the provider network and our own OpenStack OVN. Calico seems to detect the MTU just fine

## Your Environment

* Calico version: tigera-operator v3.22.0 (helm chart)
* Orchestrator version (kubernetest):  `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}`
* Operating System and version: `VERSION="20.04.3 LTS (Focal Fossa)"`

**Comment by tomastigera** [comment]
Does it apply to both upload and download direction? I mean, if you client would only upload or only download bulk data, would you see the same in both direction?

What is your VXLAN MTU size set to in Felix config?

**Comment by EugenMayer** [comment]
How do I retrieve the Felix configuration when deploying with via the operator? I expect i need to be very precise here so we do not fog out those details since those will matter most probably. I deploy via helm (tigera-operator).
Just want to be sure to hit this question.

Will do the download test and report back

**Comment by lwr20** [comment]
felix config is a fun one - there are a few places it can be set, and a hierarchy of which type of setting overrides which.
For a full picture, I'd say:

- `kubectl get felixconfig default -o yaml`
- `kubectl get pod -n calico-system calico-node-xxxx -o yaml`

**Comment by EugenMayer** [comment]
## Configuration

```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"cb43cfe5-89c7-4538-90fa-62e6232bafdb","creationTimestamp":"2022-02-10T16:35:16Z"}'
  creationTimestamp: "2022-02-10T16:35:16Z"
  generation: 2
  name: default
  resourceVersion: "1556"
  uid: cb43cfe5-89c7-4538-90fa-62e6232bafdb
spec:
  bpfLogLevel: ""
  logSeverityScreen: Info
  reportingInterval: 0s
  vxlanEnabled: true
```

`kubectl get pod -n calico-system calico-node-xxxx -o yaml | grep FELIX_`

```
    - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
    - name: FELIX_HEALTHENABLED
    - name: FELIX_TYPHAK8SNAMESPACE
    - name: FELIX_TYPHAK8SSERVICENAME
    - name: FELIX_TYPHACAFILE
    - name: FELIX_TYPHACERTFILE
    - name: FELIX_TYPHAKEYFILE
    - name: FELIX_TYPHACN
    - name: FELIX_TYPHAURISAN
    - name: FELIX_BPFENABLED
    - name: FELIX_IPV6SUPPORT
```

tigera operator is deployed using 
```
installation:
  controlPlaneTolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: "NoExecute"
  calicoNetwork:
    bgp: Disabled
    linuxDataplane: BPF
    hostPorts: Disabled
    ipPools:
      - blockSize: 26
        cidr: 10.42.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
```

**Comment by EugenMayer** [comment]
Bottom line (benchmarks)

Indeed it seems like the performance impact can only be seen when 
- the traffic comes from 'external' in terms from any network outside the control-plan.
- it can only be seen for the upload, download seems to work as expected

Considering that upload and download are extremely asymmetric, i can only assume some issue with calico since

a) if there is an issue with the underlying network, it would most probably affect both directions
b) using iptables as dataplane fixes the issue

**Comment by EugenMayer** [comment]
Is there anything I can provide / offer to move this issue forward? I would really love to use eBPF with calico, but this issue really blocks me out.

I see that likelihood has bee rated to low, i assume this means something in my setup is uncommon / unusual. May i ask which part? Openstack/RKE2? 

Thank you for working on this issue

**Comment by fasaxc** [comment]
@EugenMayer I think @sridhartigera has reproed the issue now.  We're investigating the root cause; it seems to be something to do with MTU and fragmentation being needed unexpectedly.

**Comment by EugenMayer** [comment]
@fasaxc thank you for the update and for looking after that. Considering the impact and that we actually to have unusual MTU, your assumption/observation seem to be fairly likely

**Comment by fasaxc** [comment]
It looks like Calico is generating an ICMP TOOBIG message that ends up with a bad checksum so it's not having the right effect.  We rely on sending a TOOBIG back to the client to tell it to make room for the VXLAN header.

**Comment by sridhartigera** [comment]
@EugenMayer Looks like the issue is incorrect gso detection for compatibilities related to older kernels. Have confirmed a fix for newer kernels.

**Comment by EugenMayer** [comment]
@sridhartigera sorry, kind of confused. Does the bug happen only with older kernels or with newer kernels? In other words, not sure what you patch, the kernel or calico :)

Currently we run `5.4.0-92-generic`, i guess new would be somewhat a 5.11 variant?

**Comment by tomastigera** [comment]
The issue is across all versions. Since we support kernel since 5.4, we need to use the not-always-correct test that was available in 5.4. A fix was merged in ~5.8/9 kernels, but our code does not use it yet. We confirmed that if we used the correct test in kernels where available, it would fix your problem if you were to upgrade your kernel. We need to figure out how to support old and newer kernels at the same time.

**Comment by EugenMayer** [comment]
@tomastigera so anything >= 5.8 would actually work? Did i understand this right?

Sorry my confusion, i still don't get what you want to patch. Sounds like you want to patch calico to support older kernels and old means: < 5.8

Should i try to upgrade to >= 5.8 or wait for the calico patch, what do you think? Seem like upgrading the kernel upgrade would rather mean to go from ubuntu 18 to 20, since 5.8 is not officially supported and has glitches under 18.

**Comment by fasaxc** [comment]
@EugenMayer our current understanding is that the bug exists for new and old kernels.  For new kernels, we have found a fix but the fix isn't released yet.  For old kernels, we're not yet sure if we can fix.

**Comment by EugenMayer** [comment]
@fasaxc thank you! Could you as last define, what is new (from which version) - so we can prepare an upgrade if needed? thank you

**Comment by EugenMayer** [comment]
@sridhartigera could you help me with ethool disabling `rx-gro-hw`? Not sure, never did it and if i fail, the entire test will be useless without you knowing about it. So i guess we should align/ensure i disable it the right way. Sorry for the extra effort

**Comment by sridhartigera** [comment]
@EugenMayer Command for disabling rx-gro-hw ```ethtool -K <interface_name> rx-gro-hw off```. Please ensure it is turned off using this command ```ethtool -k <interface_name>```

**Comment by sridhartigera** [comment]
@EugenMayer Did you get a chance to run the tests with ```rx-gro-hw``` turned off?

**Comment by EugenMayer** [comment]
@sridhartigera sorry, i'am currently not able to test this since our dev-cluser is broken due to some odd OpenStack issues - since it is only the dev cluster, i'am currently not able to work on that dedicated. I plan to be able to run in this test in the next week.

Really sorry to not being able to push this further right now

**Comment by EugenMayer** [comment]
So today I was able to do some tests. I'm currently testing with calico 3.21.4 since i cannot install 3.22.1 - see #5775 

Before disabling `rx-gro-hw off` the entire thing is more broken than I used to see - after the first package to iperf, the entire connection is broken for a couple of seconds. Not only to iperf3, also Lens is no longer able to reach the cluster (so no kubeapi). This last for about 60 seconds.

It seems that the tigera operator has issues (and is restarted)

```
E0321 09:10:16.507231       1 leaderelection.go:321] error retrieving resource lock tigera-operator/operator-lock: Get "https://10.10.6.10:6443/api/v1/namespaces/tigera-operator/configmaps/operator-lock": context deadline exceeded
I0321 09:10:16.507273       1 leaderelection.go:278] failed to renew lease tigera-operator/operator-lock: timed out waiting for the condition
{"level":"error","ts":1647853816.507302,"logger":"setup","msg":"problem running manager","error":"leader election lost","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nmain.main\n\t/go/src/github.com/tigera/operator/main.go:279\nruntime.main\n\t/usr/local/go-cgo/src/runtime/proc.go:2
```

```
iperf3 -R -c 10.10.6.10 -p 5201
Connecting to host 10.10.6.10, port 5201
Reverse mode, remote host 10.10.6.10 is sending
[  5] local 10.10.0.3 port 49892 connected to 10.10.6.10 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  2.33 MBytes  19.5 Mbits/sec                  
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec                  
^C[  5]   6.00-6.84   sec  0.00 Bytes  0.00 bits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-6.84   sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-6.84   sec  2.33 MBytes  2.85 Mbits/sec                  receiver
iperf3: interrupt - the client has terminated
```

Again, doing the same to the server agent itself (so no calico involved) works, so it is not an issue with the underlying / physical network

```
Connecting to host 10.10.6.10, port 30000
Reverse mode, remote host 10.10.6.10 is sending
[  5] local 10.10.0.3 port 33114 connected to 10.10.6.10 port 30000
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   106 MBytes   889 Mbits/sec                  
[  5]   1.00-2.00   sec   106 MBytes   892 Mbits/sec                  
[  5]   2.00-3.00   sec   106 MBytes   893 Mbits/sec                  
[  5]   3.00-4.00   sec   107 MBytes   894 Mbits/sec                  
[  5]   4.00-5.00   sec   106 MBytes   889 Mbits/sec                  
[  5]   5.00-6.00   sec   106 MBytes   887 Mbits/sec                  
[  5]   6.00-7.00   sec   106 MBytes   892 Mbits/sec                  
[  5]   7.00-8.00   sec   106 MBytes   891 Mbits/sec                  
[  5]   8.00-9.00   sec  81.6 MBytes   685 Mbits/sec                  
[  5]   9.00-10.00  sec   103 MBytes   868 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.01 GBytes   870 Mbits/sec  179             sender
[  5]   0.00-10.00  sec  1.01 GBytes   868 Mbits/sec                  receiver

iperf Done.
```

**Comment by EugenMayer** [comment]
Finally using `ethtool -K ens3 rx-gro-hw off` on the server node (control plane) only (workloads i did not change) we have full speed on no crashing network

```
iperf3 -R -c 10.10.6.10 -p 5201
Connecting to host 10.10.6.10, port 5201
Reverse mode, remote host 10.10.6.10 is sending
[  5] local 10.10.0.3 port 49904 connected to 10.10.6.10 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   101 MBytes   851 Mbits/sec                  
[  5]   1.00-2.00   sec   105 MBytes   877 Mbits/sec                  
[  5]   2.00-3.00   sec   105 MBytes   883 Mbits/sec                  
[  5]   3.00-4.00   sec   105 MBytes   880 Mbits/sec                  
[  5]   4.00-5.00   sec   105 MBytes   878 Mbits/sec                  
[  5]   5.00-6.00   sec   105 MBytes   882 Mbits/sec                  
[  5]   6.00-7.00   sec   105 MBytes   880 Mbits/sec                  
[  5]   7.00-8.00   sec   105 MBytes   883 Mbits/sec                  
[  5]   8.00-9.00   sec   105 MBytes   883 Mbits/sec                  
[  5]   9.00-10.00  sec   105 MBytes   880 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.03 GBytes   881 Mbits/sec  504             sender
[  5]   0.00-10.00  sec  1.02 GBytes   878 Mbits/sec                  receiver

iperf Done.
```

So i can confirm that disabling `rx-gro-hw` via

```
ethtool -K ens3 rx-gro-hw off
```

Fixes the issue. Are you people planning to fix this for kernels < 5.7 without disabling this option, or is this the expected work-around? 

Thank you for all the work!

**Comment by sridhartigera** [comment]
I don't think we will be able to fix this for kernels < 5.7 without disabling ```rx-gro-hw```. Hence this is the expected work-around. Thanks for confirming that things worked for you as well.

**Comment by sridhartigera** [comment]
@EugenMayer Calico v3.23 will include the patch for kernels above 5.7. Mid April is the timeline we are looking to release v3.23.
