### ISSUE TITLE
cross-subnet mode ,  I added a new node to the kubernetes cluster. The network segment of this node is different from the network segment of the original kubernetes cluster .  

### ISSUE THREAD

**Issue by deco-zhang** [projectcalico/calico#5738]
cross-subnet mode ,  I added a new node to the kubernetes cluster. The network segment of this node is different from the network segment of the original kubernetes cluster .  

kubectl -n kube-system get pods
NAME                                        READY   STATUS    RESTARTS   AGE
calico-kube-controllers-7f6768fdfb-5r56c    1/1     Running   0          65d
calico-node-6zmkn                           1/1     Running   0          34h
calico-node-7wwsh                           1/1     Running   0          24h
calico-node-8jbm9                           1/1     Running   0          34h
calico-node-bzb4s                           1/1     Running   0          34h
calico-node-hq8bg                           1/1     Running   0          34h
calico-node-n9shn                           1/1     Running   0          34h
calico-node-rgqnk                           1/1     Running   0          34h
calico-node-tc96j                           1/1     Running   0          34h

calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+------------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+--------------+-------------------+-------+------------+-------------+
| 10.21.1.171  | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.2.250  | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.0.81   | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.1.236  | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.2.185  | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.0.26   | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.1.27   | node-to-node mesh | up    | 2022-03-09 | Established |
| 10.21.0.153  | node-to-node mesh | up    | 2022-03-10 | Established |
+--------------+-------------------+-------+------------+-------------+

calicoctl get ipPool -o yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: 2022-01-04T12:34:19Z
    name: default-ipv4-ippool
    resourceVersion: "14319405"
    uid: 31d03d0e-6645-4561-8ee2-c90a4ff4aebc
  spec:
    blockSize: 26
    cidr: 172.244.0.0/16
    ipipMode: CrossSubnet
    natOutgoing: true
    nodeSelector: all()
kind: IPPoolList
metadata:
  resourceVersion: "14641912"

new node :

[root@prod-k8s-node08 centos]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.21.0.1       0.0.0.0         UG    0      0        0 ens5
10.21.0.0       0.0.0.0         255.255.255.0   U     0      0        0 ens5
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.244.23.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.244.23.193  0.0.0.0         255.255.255.255 UH    0      0        0 cali630f2bd5792
172.244.23.199  0.0.0.0         255.255.255.255 UH    0      0        0 cali98c953cecce
172.244.40.64   10.21.1.171     255.255.255.192 UG    0      0        0 tunl0
172.244.146.192 10.21.2.185     255.255.255.192 UG    0      0        0 tunl0
172.244.153.64  10.21.1.27      255.255.255.192 UG    0      0        0 tunl0
172.244.178.128 10.21.0.26      255.255.255.192 UG    0      0        0 ens5
172.244.181.128 10.21.2.250     255.255.255.192 UG    0      0        0 tunl0
172.244.208.64  10.21.0.81      255.255.255.192 UG    0      0        0 ens5
172.244.211.192 10.21.1.236     255.255.255.192 UG    0      0        0 tunl0
172.244.215.192 10.21.0.166     255.255.255.192 UG    0      0        0 ens5

Behavior ： 

1.  the new node （prod-k8s-node08）， same subnet segment with ens5 （10.21.0.0） , pod  address can Normal communication .
2.  the new node （prod-k8s-node08），different subnet segment (10.21.1.x、10.21.2.x)  pod  address  cannot communicate 
3.  if  use 10.21.1.x or 10.21.2.x node ping prod-k8s-node08 , then prod-k8s-node08  can communicate pod  address , but a few minutes   Communication failure .

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.8.9
* Orchestrator version (e.g. kubernetes, mesos, rkt):  1.21.9
* Operating System and version:  5.4.168-1.el7
* AWS EC2 to Delpoy kubernetes

**Comment by caseydavenport** [comment]
IIUC, you're saying cross-subnet communications for pods aren't working? 

You should check that your firewall is allowing the encapsulated packets and also check to make sure that the packets are indeed being sent over the tunnel.

**Comment by deco-zhang** [comment]
> IIUC, you're saying cross-subnet communications for pods aren't working?
> 
> You should check that your firewall is allowing the encapsulated packets and also check to make sure that the packets are indeed being sent over the tunnel.

1.  the packets are indeed being sent over the tunnel.

tcpdump -vvX -i tunl0

03:58:24.640665 IP (tos 0x0, ttl 64, id 47716, offset 0, flags [DF], proto ICMP (1), length 84)
    ip-10-244-195-64.ap-south-1.compute.internal > ip-10-244-227-192.ap-south-1.compute.internal: ICMP echo request, id 16914, seq 61, length 64
        0x0000:  4500 0054 ba64 4000 4001 c35b 0af4 c340  E..T.d@.@..[...@
        0x0010:  0af4 e3c0 0800 d79a 4212 003d 601a 2c62  ........B..=`.,b
        0x0020:  0000 0000 89c6 0900 0000 0000 1011 1213  ................
        0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
        0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
        0x0050:  3435 3637                                4567

2. how can i  check that your firewall is allowing the encapsulated packets ?

**Comment by deco-zhang** [comment]
> > IIUC, you're saying cross-subnet communications for pods aren't working?
> > You should check that your firewall is allowing the encapsulated packets and also check to make sure that the packets are indeed being sent over the tunnel.
> 
> 1. the packets are indeed being sent over the tunnel.
> 
> tcpdump -vvX -i tunl0
> 
> 03:58:24.640665 IP (tos 0x0, ttl 64, id 47716, offset 0, flags [DF], proto ICMP (1), length 84) ip-10-244-195-64.ap-south-1.compute.internal > ip-10-244-227-192.ap-south-1.compute.internal: ICMP echo request, id 16914, seq 61, length 64 0x0000: 4500 0054 ba64 4000 4001 c35b 0af4 c340 E..T.d@.@..[...@ 0x0010: 0af4 e3c0 0800 d79a 4212 003d 601a 2c62 ........B..=`.,b 0x0020: 0000 0000 89c6 0900 0000 0000 1011 1213 ................ 0x0030: 1415 1617 1819 1a1b 1c1d 1e1f 2021 2223 .............!"# 0x0040: 2425 2627 2829 2a2b 2c2d 2e2f 3031 3233 $%&'()*+,-./0123 0x0050: 3435 3637 4567
> 
> 2. how can i  check that your firewall is allowing the encapsulated packets ?

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/101389472/158003048-363871a4-837b-4694-8030-249b2745898b.png">

**Comment by caseydavenport** [comment]
> how can i check that your firewall is allowing the encapsulated packets ?

Network requirements are laid out here: https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#network-requirements

You can also check on the receiving node to see if the packets are making it to the remote node's tunnel device.

**Comment by deco-zhang** [comment]
> 

if use receiving node  ping  remote node ,   communicate tunl can be use , but a few minutes Communication failure .

**Comment by deco-zhang** [comment]
> > how can i check that your firewall is allowing the encapsulated packets ?
> 
> Network requirements are laid out here: https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#network-requirements
> 
> You can also check on the receiving node to see if the packets are making it to the remote node's tunnel device.
[diags-20220316_074630.tar.gz](https://github.com/projectcalico/calico/files/8259914/diags-20220316_074630.tar.gz)

 diagnostics log  can you help to check it.

**Comment by deco-zhang** [comment]
> > how can i check that your firewall is allowing the encapsulated packets ?
> 
> Network requirements are laid out here: https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#network-requirements
> 
> You can also check on the receiving node to see if the packets are making it to the remote node's tunnel device.

@caseydavenport can you help me .

**Comment by caseydavenport** [comment]
> if use receiving node ping remote node , communicate tunl can be use , but a few minutes Communication failure .

I don't understand this.

**Comment by deco-zhang** [comment]
> > if use receiving node ping remote node , communicate tunl can be use , but a few minutes Communication failure .
> 
> I don't understand this.

thanks for the reply  @caseydavenport 

[root@prod-k8s-master01 centos]# kubectl get nodes 
NAME                STATUS   ROLES                  AGE   VERSION
prod-k8s-master01   Ready    control-plane,master   81d   v1.21.8
prod-k8s-master02   Ready    control-plane,master   81d   v1.21.8
prod-k8s-master03   Ready    control-plane,master   81d   v1.21.8
prod-k8s-node01     Ready    <none>                 81d   v1.21.8
prod-k8s-node02     Ready    <none>                 81d   v1.21.8
prod-k8s-node03     Ready    <none>                 76d   v1.21.8
prod-k8s-node04     Ready    <none>                 40d   v1.21.9
prod-k8s-node05     Ready    <none>                 33d   v1.21.9
prod-k8s-node08     Ready    <none>                 11d   v1.21.9

[root@prod-k8s-node08 centos]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.21.0.1       0.0.0.0         UG    0      0        0 ens5
10.21.0.0       0.0.0.0         255.255.255.0   U     0      0        0 ens5
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.244.23.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.244.23.193  0.0.0.0         255.255.255.255 UH    0      0        0 cali630f2bd5792
172.244.23.199  0.0.0.0         255.255.255.255 UH    0      0        0 cali98c953cecce
172.244.40.64   10.21.1.171     255.255.255.192 UG    0      0        0 tunl0
172.244.146.192 10.21.2.185     255.255.255.192 UG    0      0        0 tunl0
172.244.153.64  10.21.1.27      255.255.255.192 UG    0      0        0 tunl0
172.244.178.128 10.21.0.26      255.255.255.192 UG    0      0        0 ens5
172.244.181.128 10.21.2.250     255.255.255.192 UG    0      0        0 tunl0
172.244.208.64  10.21.0.81      255.255.255.192 UG    0      0        0 ens5
172.244.211.192 10.21.1.236     255.255.255.192 UG    0      0        0 tunl0
172.244.215.192 10.21.0.166     255.255.255.192 UG    0      0        0 ens5


1. node08 is new node add in cluster  ， if use node08  to ping node05  tunl0 address (172.244.40.64)  Communication failue
2. but if use node05  ping  node08 tunl0 address (172.244.23.192)  can Communication
3. then use node08 ping node05 also can Communication
4. a few minutes later use node08 ping node05 Communication failure

The communication link can only be used by the old nodes of the cluster, and it will fail after a few minutes.

**Comment by song-jiang** [comment]
As Casey mentioned above, I suggest you to run a debug process:
1. Access from pod (on node05) to pod (on node 08), it will fail according to you description.
2. Tcpdump to see if the packet going through the tunnel device on node05. 
3. Tcpdump to see if the packet going through the tunnel device on node08.

It is not necessary to ping ip address of the tunnel device on other node at moment

**Comment by caseydavenport** [comment]
> Calico version v3.8.9

Are you really using Calico v3.8.9? if so, you definitely need to upgrade. This is an ancient version and many many bugs have been fixed since then.

**Comment by deco-zhang** [comment]
> 

The cluster was deployed using version 3.8.9, and now it has been upgraded to 3.21. The problem still exists

**Comment by caseydavenport** [comment]
Have you allowed IPIP - IP protocol 4 - in your security groups between nodes?

 I have seen this behavior in the past on AWS if protocol 94 is used instead of protocol 4.

**Comment by deco-zhang** [comment]
> Have you allowed IPIP - IP protocol 4 - in your security groups between nodes?
> 
> I have seen this behavior in the past on AWS if protocol 94 is used instead of protocol 4.

@caseydavenport 

this right ， past on all protocol , then can Communication  ，very thanks 。
