### ISSUE TITLE
Release notes not available after publishing GitHub release

### ISSUE THREAD

**Issue by invidian** [projectcalico/calico#6048]
## Expected Behavior

Only publish releases which triggers user notifications when all release artifacts are ready for consumption.

## Current Behavior

7h after https://github.com/projectcalico/calico/releases/tag/v3.23.0 has been created, the only provided link there, https://projectcalico.docs.tigera.io/archive/v3.23/release-notes/ still returns 404. This is annoying for people eager to try new versions or simply waiting for new feature or a bug fix and makes them periodically, manually poll for availability of the release instead of just getting notified when everything is ready to update. This may also delay the feedback on new releases from early bug reporters.

This release is generally not the first one when this occurs.

## Possible Solution

Perhaps CI pipelines should be triggered on release tag push or manually and the release should be published only after all release pipelines has succeeded.

## Context

I like to keep my clusters up to date with upstream and once I get the GitHub notification/email about the new release, I keep it in my inbox until the update is rolled out.

**Comment by caseydavenport** [comment]
Yep I agree. This is a consequence of how our documentation and release notes are structured at the moment. I think the solution to this is to get rid of the dependency on the documentation for hosting the release notes and manifests, so that as soon as the tag is pushed the release notes and manifests are available.

I don't know that there is an easy way to guarantee that the documentation itself is up-to-date, there will fundamentally be an ordering dependency on publishing the release artifacts, verifying them, and then updating the documentation to reference them. However, we can certainly switch to a model where the release notes and manifests aren't dependent on docs.projectcalico.org.

**Comment by caseydavenport** [comment]
FWIW, here is the release notes file that will ultimately be generated into the docs: https://github.com/projectcalico/calico/blob/v3.23.0/calico/_includes/release-notes/v3.23.0-release-notes.md

**Comment by invidian** [comment]
Link to the release notes in [v3.24.0](https://github.com/projectcalico/calico/releases/tag/v3.24.0) does not work either now :(

**Comment by caseydavenport** [comment]
@invidian bah, yeah it was meant to point at this: https://github.com/projectcalico/calico/blob/release-v3.24/calico/_includes/release-notes/v3.24.0-release-notes.md

**Comment by caseydavenport** [comment]
This should fix it... https://github.com/projectcalico/calico/pull/6584

**Comment by invidian** [comment]
Thanks for fixing it quickly :)

**Comment by invidian** [comment]
I'm sorry for being annoying, but in https://github.com/projectcalico/calico/releases/tag/v3.24.1 the link is still broken. I guess the fix has not been backported?

**Comment by caseydavenport** [comment]
:facepalm: not annoying at all.

Let me investigate.

**Comment by caseydavenport** [comment]
Sigh. This should do it: https://github.com/projectcalico/calico/pull/6631

Sometimes I'm not very bright :sweat_smile:

**Comment by invidian** [comment]
This issue should probably be closed, **but** the link in https://github.com/projectcalico/calico/releases/tag/v3.26.0 to the changelog, which is https://github.com/projectcalico/calico/blob/v3.26.0/calico/_includes/release-notes/v3.26.0-release-notes.md, is returning 404 now.

**Comment by caseydavenport** [comment]
Sigh, of course it is. Thanks again for the heads up 😅 

These got moved as part of our docs migration, looks like the tool wasn't updated.

This is the new link: https://github.com/projectcalico/calico/blob/v3.26.0/release-notes/v3.26.0-release-notes.md

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/calico/pull/7718

**Comment by invidian** [comment]
It seem fix from #7718 did not work for latest release: https://github.com/projectcalico/calico/releases/tag/v3.26.1. Maybe it wasn't backported?

**Comment by caseydavenport** [comment]
Looks like I never actually back-ported it. 

This is it: https://github.com/projectcalico/calico/pull/7815
