### ISSUE TITLE
Error creating: pods "csi-node-driver-"

### ISSUE THREAD

**Issue by Jeansen** [projectcalico/calico#7003]
Error creating: pods "csi-node-driver-" is forbidden: error looking up service account calico-system/csi-node-driver: serviceaccount "csi-node-driver" not found

## Expected Behavior
Installation with helm finishes without errors.

## Current Behavior
Installed the latest version via helm. Looking at the cluster, I see that the daemon-set 'csi-node-driver' hast the following error:
Error creating: pods "csi-node-driver-" is forbidden: error looking up service account calico-system/csi-node-driver: serviceaccount "csi-node-driver" not found

## Possible Solution
kubectl create serviceaccount csi-node-driver -n calico-system

## Steps to Reproduce (for bugs)
1. Created a cluster with Kubernetes 1.25.3, 4 nodes, 1 master
2. helm upgrade --install --wait calico projectcalico/tigera-operator --create-namespace --namespace tigera-operator --version=v3.24.5
3.
4.

**Comment by xoxys** [comment]
Same here. For me, the latest working release is https://raw.githubusercontent.com/projectcalico/calico/v3.24.2/manifests/tigera-operator.yaml while all newer releases fail to set up `daemonset/csi-node-driver`. I have tested it with a fresh k3s host (a fresh setup for each calico version):

NAME         STATUS   ROLES                           AGE     VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION                CONTAINER-RUNTIME
rocky9-k3s   Ready    control-plane,k3s-node,master   4m14s   v1.25.3+k3s1   10.168.42.2   <none>        Rocky Linux 9.0 (Blue Onyx)   5.14.0-70.22.1.el9_0.x86_64   containerd://1.6.8-k3s1

The K3s setup was the same on each test, only the calico manifest version was changed.

**Comment by jameshearttech** [comment]
I have a self-managed 1.25.3 k8s cluster setup with kubeadm on Ubuntu server 22.04.1 LTS. The daemonset pods fail to start because of a missing serviceaccount looks like.

    $ uname -a
    Linux dev-master0 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    $ kubectl version --short
    Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
    Client Version: v1.25.3
    Kustomize Version: v4.5.7
    Server Version: v1.25.3
    $ kubectl get daemonset/csi-node-driver -n calico-system
    NAME              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
    csi-node-driver   0         0         0       0            0           kubernetes.io/os=linux   16d
    $ kubectl describe daemonset/csi-node-driver -n calico-system | grep "Error"
      Warning  FailedCreate  76s (x1169 over 12d)  daemonset-controller  Error creating: pods "csi-node-driver-" is forbidden: error looking up service account calico-system/csi-node-driver: serviceaccount "csi-node-driver" not found
    $ kubectl get serviceaccount -A | grep "csi-node-driver"
    $

**Comment by lwr20** [comment]
pinging @Josh-Tigera

**Comment by Josh-Tigera** [comment]
I committed a fix to this in the operator that will be available in v3.24.6 and onward.

**Comment by jameshearttech** [comment]
> I committed a fix to this in the operator that will be available in v3.24.6 and onward.

Awesome. Any idea when 3.24.6 will be released?

**Comment by Josh-Tigera** [comment]
I'm not aware of exact timelines unfortunately as I'm not involved in the release process.

**Comment by caseydavenport** [comment]
CC @mgleung

**Comment by caseydavenport** [comment]
Closing as a fix has been merged and backported.

**Comment by xoxys** [comment]
@caseydavenport @Josh-Tigera can provide a link to the related PR? For me, it's still not working even with the `v3.24.5` release:

```
❯ kubectl describe daemonsets.apps -n calico-system csi-node-driver 
Name:           csi-node-driver
Selector:       k8s-app=csi-node-driver
Node-Selector:  kubernetes.io/os=linux
Labels:         <none>
Annotations:    deprecated.daemonset.template.generation: 2
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/name=csi-node-driver
                    k8s-app=csi-node-driver
                    name=csi-node-driver
  Service Account:  csi-node-driver
  Containers:
   calico-csi:
    Image:      docker.io/calico/csi:v3.24.5
    Port:       <none>
    Host Port:  <none>
    Args:
```

```
calico-system      5m12s       Warning   Unhealthy                    pod/calico-node-4s7br                           Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
calico-system      5m11s       Warning   Unhealthy                    pod/calico-node-4s7br                           Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
calico-system      5m3s        Warning   FailedCreate                 daemonset/csi-node-driver                       Error creating: pods "csi-node-driver-" is forbidden: error looking up service account calico-system/csi-node-driver: serviceaccount "csi-node-driver" not found
```

**Comment by lwr20** [comment]
To repeat what Josh said:

> I committed a fix to this in the operator that will be available in **v3.24.6** and onward.

**Comment by xoxys** [comment]
:facepalm: sorry totally missed the version information... sorry again for the noise

**Comment by lwr20** [comment]
It would be helpful if we had a link to the PR though.  Any chance @Josh-Tigera?

**Comment by taxilian** [comment]
so... a month and a half old and there is no workaround for this? no fix? does it not affect everyone or something?

I'm very confused -- this has completely blocked my ability to use the current release so it seems like it'd be a high priority, but if it's taken this long it seems like I must be missing something?

does the solution of just creating a serviceaccount with that name work?

**Comment by onedr0p** [comment]
I've just pinned my k3s cluster to 1.24.x and calico to 3.24.2 until a new release of calico is made.

**Comment by Jeansen** [comment]
> does the solution of just creating a serviceaccount with that name work?

For me that works, but why don't you try it yourself? creating a SA is am matter of less than a minute.

**Comment by taxilian** [comment]
Yeah, I have tried it and it seems to be working so far. I also looked at
the current branch and it appears that the "fix" is going to be just
removing the need to have the service account.

**Comment by onedr0p** [comment]
For anyone lazy (like me) I wrote out the SA and Secret you need to apply

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node-driver
  namespace: calico-system
secrets:
  - name: csi-node-driver
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: csi-node-driver
  namespace: calico-system
  annotations:
    kubernetes.io/service-account.name: csi-node-driver
```

**Comment by Josh-Tigera** [comment]
Here's the link to the fix for anyone who wanted to have a look: https://github.com/tigera/operator/pull/2282

**Comment by willzhang** [comment]
resolved
