### ISSUE TITLE
calico/node-driver-registrar:v3.25.0-s390x apparently has a x86-64 binary.

### ISSUE THREAD

**Issue by boscojr** [projectcalico/calico#7254]
I'm trying to install calico 3.25.0 with k8s 1.26 on s390x Linux machine via tigera operator. 

## Expected Behavior

Container is running

## Current Behavior

Container node-driver-registrar is in CrashLoopBackOff.

```
$ kubectl -n calico-system   logs   csi-node-driver-sdrpd -c csi-node-driver-registrar
exec /usr/local/bin/node-driver-registrar: exec format erro
```

I checked the binary in image and i could see that others binary are in s390x but node-driver-registrar is in x86-64 :

```
$ ctr images mount quay.io/calico/node-driver-registrar:v3.25-s390x /tmp/teste/
$  file /tmp/teste/usr/local/bin/node-driver-registrar
/tmp/teste/usr/local/bin/node-driver-registrar: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

$ file /tmp/teste/bin/busybox 
/tmp/teste/bin/busybox: ELF 64-bit MSB shared object, IBM S/390, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-s390x.so.1, stripped
```

## Steps to Reproduce (for bugs)

1. In a s390x machine run  docker run  quay.io/calico/node-driver-registrar:release-v3.25-s390x 
2. container exits with message: standard_init_linux.go:228: exec user process caused: exec format error
3.
4.

## Your Environment

* Calico version: 3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.26.0
* Operating System and version: Red Hat 8.7 s390
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I believe this should fix it https://github.com/projectcalico/calico/pull/7315

**Comment by sulaweyo** [comment]
This is still happening on v3.29.0 
exec /usr/bin/node-driver-registrar: exec format error
as mentioned on [8784](https://github.com/projectcalico/calico/issues/8784)
