### ISSUE TITLE
CSI node driver limits/requests issue using operator

### ISSUE THREAD

**Issue by 6ripley** [projectcalico/calico#7561]
## Expected Behavior
Limits/requests should be set correctly for CSI node driver

## Current Behavior
I'm unable to set limits/requests by editing installation file or daemonset

## Steps to Reproduce (for bugs)
1. Install operator 
2. Trigger installation 
3. Edit installation resource to set requests/limits for csi node driver

## Context
Hello,
I'm trying to make calico pods guaranteed by setting resource limits and requests within InstallationSpec, I can see for the CSINodeDriverDaemonset that the docs are pointing to the reference that should be under InstallationSpec but when redirected to the InstallationSpec, it does not list it and is not mentioned under ComponentResources deprecation info.
[https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.CSINodeDriverDaemonSet](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.CSINodeDriverDaemonSet)
[https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.InstallationSpec](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.InstallationSpec)

**Comment by tmjd** [comment]
I believe this is fixed with the merging of https://github.com/tigera/docs/pull/638.

**Comment by Mohsen51** [comment]
I think this documentation update does not solve the issue which is how to set Limits/requests correctly for CSI node driver ...

**Comment by caseydavenport** [comment]
Yep - there's only reference documentation for this right now, but there's no walkthrough guide.

I raised this issue against the documentation for this: https://github.com/tigera/docs/issues/673

I think this issue can stay closed - the code supports it, it's just a documentation gap.
