### ISSUE TITLE
Missing changelog file for v3.26.4

### ISSUE THREAD

**Issue by xoxys** [projectcalico/calico#8236]
The GitHub release page for v3.26.4 has a dead link to the changelog of this version under "Release notes can be found [on GitHub](https://github.com/projectcalico/calico/blob/v3.26.4/release-notes/v3.26.4-release-notes.md)".

**Comment by danudey** [comment]
Hey @xoxys, thanks for catching this! We've committed the release notes now, and all should be well. Apologies for the confusion!

**Comment by sdwilsh** [comment]
@danudey, the URL in the issue still is a 404.  It's the same URL that's in the GitHub release text: https://github.com/projectcalico/calico/releases/tag/v3.26.4

**Comment by xoxys** [comment]
For ref if someone is looking for the file, it was added to the release branch https://github.com/projectcalico/calico/blob/release-v3.26/release-notes/v3.26.4-release-notes.md. As the tag is immutable, someone might want to change the ink in the GitHub release description manually.
