### ISSUE TITLE
Calico v3.27.0 not working with Tigera v1.32.3

### ISSUE THREAD

**Issue by Rajesh-Gurjar** [projectcalico/calico#8407]
Hi,

I'm deploying Tigera v1.32.3 which uses calico v3.27.0 and the pod is unable to start. It is for RHEL 8. k8s version is 1.27. 

## Expected Behavior

It should work as expected. Tigera v1.30.9 & v1.30.8 is working fine with v3.26.4 & v3.26.3 respectively. 

## Current Behavior

```
$ k logs calico-node-9cv7m
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init)
calico-node: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
Calico node failed to start
```

In the working version libpcap.so.1.9.1 is installed. Can you please help why an older lib is requested by newer calico version? 
The Tigera pod is running and working as expected, no logs are there related to this error.

**Comment by caseydavenport** [comment]
I noticed this line in our Dockerfile, which seems relevant: https://github.com/projectcalico/calico/blob/711528eeb00fd90dde38e87ecee7d1c155cab0e6/node/Dockerfile.amd64#L238-L240

From this PR: https://github.com/projectcalico/calico/commit/4bbda7d465f5df20ffb18c2f7b897cf899e9bc46

@sridhartigera any thoughts on this one?

**Comment by hjiawei** [comment]
Ref https://github.com/tigera/operator/issues/3114.

**Comment by Rajesh-Gurjar** [comment]
It worked after creating the symlink. Thanks for help.

**Comment by hjiawei** [comment]
Thanks for reporting this issue @lou-lan. I believe [these lines](https://github.com/projectcalico/calico/pull/8533/files#diff-c6e82bd404a904c10b9a0756d78d913a8a5e2ff833fefd384c80af1d7c93c3bbR240-R243) in PR #8533 should fix the arm64 calico/node issue. amd64 and the main branch calico/node should not be affected.

**Comment by blueberrysnapple** [comment]
Hi @hjiawei I'm on version 3.27.2

But still getting this on arm. 

```
kubectl logs calico-node-nbtln -n calico-system
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), install-cni (init)
calico-node: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
Calico node failed to start
```
```
dpkg -l | grep libpcap
ii  libpcap0.8:arm64                         1.10.1-4build1                          arm64        system interface for user-level packet capture
```

```
find /usr/ -iname "*libpcap*"
/usr/lib/aarch64-linux-gnu/libpcap.so.0.8
/usr/lib/aarch64-linux-gnu/libpcap.so.1.10.1
```

**Comment by hjiawei** [comment]
@blueberrysnapple This fix was late for v3.27.2 (was v3.27.1) so please wait for the coming v3.27.3 release.

**Comment by blueberrysnapple** [comment]
@hjiawei Hey, I'm looking at doing my own workaround here, and I'm seeing that the fix is in for amd64 but not for arm64 which is what I have and I'm having this problem. 

Perhaps I misunderstand, I'm fairly new at all this, but that it would be good to let you know.

**Comment by hegerdes** [comment]
Also faced this issue - rolled back to  3.27.9.

Is there an ETA for v3.27.3?

**Comment by marvinlnnx** [comment]
any update for v3.27.3 please ?
