### ISSUE TITLE
Calico does not handle OS built without IPv6 support

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#989]
Running Calico on a private build of RHEL 7.2 (3.10.0_327).  The build does not have IPv6 support enabled.

Although we didn't spot any failures with Calico (because we built a version that disabled all IPv6 table configuration) - code reading suggests that it will be a problem.

Can we have a mechanism for disabling IPv6.  How about checking for the existence of "/proc/sys/net/ipv6".

**Comment by neiljerram** [comment]
Is this issue resolved now?  It looks like it might be, given that merge.

**Comment by robbrockbank** [comment]
No not resolved.  The merged change was just for cailcoctl.  We still need a fix in Felix to stop programming any IPv6 stuff when IPv6 is not available on the OS.

**Comment by fasaxc** [comment]
Fixed in #996

**Comment by johanot** [comment]
I know that this issue i pretty old, but ... it could be nice to explicitly be able to disable ipv6 support with a config option? I couldn't find any discussion on this anywhere?

**Comment by neiljerram** [comment]
@johanot There is now an `ipv6Support` option.  Please see https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/felixconfig.

**Comment by johanot** [comment]
@neiljerram Found it myself almost the same second as you commented. Don't know why it took me so long. Still new to Calico. Thanks a ton!
